apiVersion: v1
kind: Service
metadata:
  labels:
    victoriametrics.service: vminsert
  name: vminsert
  namespace: mobin-monitor
spec:
  ports:
    - name: "8480"
      port: 8480
      targetPort: 8480
  selector:
    victoriametrics.service: vminsert
  type: LoadBalancer  #利用LoadBalancer达到负载均衡的作用