apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    victoriametrics.service: vmagent01
  name: vmagent01
  namespace: mobin-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      victoriametrics.service: vmagent01
  template:
    metadata:
      labels:
        victoriametrics.service: vmagent01
    spec:
      serviceAccountName: prometheus
      securityContext:
        runAsUser: 0
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: consul-template-config
        configMap:
          name: consul-template-config-five
      - name: prometheus-discovery-config
        configMap:
          name: prometheus-discovery-config-five
      - name: consul-template-to-prometheus-config
        hostPath:
          path: /data/prometheus-config-five
      - name: consul-template-log
        hostPath:
          path: /data/consul-log-five
      - name: prometheus-config
        configMap:
          name: prometheus-config-five
      initContainers:
      - name: close-tcp-timestamps
        image: maven.mobin.com.cn:8084/docker.io/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args: ["sysctl -w net.ipv4.tcp_timestamps=0","sysctl -w net.ipv4.tcp_tw_recycle=0"]
        securityContext:
          privileged: true
      containers:
      - name: consul-template
        image: maven.mobin.com.cn:8084/docker.io/hashicorp/consul-template:alpine
        imagePullPolicy: IfNotPresent
        command: ['sh','-c', 'mkdir -p /tmp/consul-log;nohup consul-template -config  /config/consul-template.conf > /tmp/consul-log/consul-template.log 2>&1']
        volumeMounts:
        - mountPath: /config/
          name: consul-template-config
        - mountPath: /config/prometheus
          name: prometheus-discovery-config
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: consul-template-to-prometheus-config
          mountPath: /tmp/consul-template/
        - name: consul-template-log
          mountPath: /tmp/consul-log/
      - name: vmagent01
        args:
        - --promscrape.config=/etc/prometheus/prometheus.yaml
        - --remoteWrite.url=http://vminsert:8480/insert/0/prometheus/
        - --promscrape.configCheckInterval=1m
        - --remoteWrite.flushInterval=10s
        - --enableTCP6=true
        image: maven.mobin.com.cn:8084/docker.io/victoriametrics/vmagent:latest
        ports:
          - containerPort: 8429
        resources:
            requests:
              memory: "2Gi"
              cpu: "3"
            limits:
              memory: "10Gi"
              cpu: "4"
        volumeMounts:
          - mountPath: /etc/prometheus/
            name: prometheus-config
          - name: consul-template-to-prometheus-config
            mountPath: /tmp/consul-template/
          - name: host-time
            mountPath: /etc/localtime
            readOnly: true
      restartPolicy: Always