apiVersion: v1
kind: Service
metadata:
  labels:
    victoriametrics.service: vmstorage01
  name: vmstorage01
  namespace: mobin-monitor
spec:
  ports:
    - name: "8482"
      port: 8482
      targetPort: 8482
    - name: "8400"
      port: 8400
      targetPort: 8400
    - name: "8401"
      port: 8401
      targetPort: 8401
  selector:
    victoriametrics.service: vmstorage01
  type: NodePort
status:
  loadBalancer: {}