apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: mobin-monitor
data:
  grafana.ini: |
    [server]
    [smtp]
    enabled = true
    host = xx.xxx.com.cn:25
    user = xxxx@xxx.com.cn
    password =
    skip_verify = true
    from_address = xxx@xxx.com.cn
    [alerting]
    enabled = true
    execute_alerts = true

    [database]
    type = mysql
    host = xxx:3343
    name = grafana
    user = "grafanaopr"
    password = """abc#"""
  
    [session]
    provider = mysql
    provider_config = grafanaopr:grafOpr888#@tcp(xxx:3343)/grafana
    cookie_name = grafana_session_mobin
    cookie_secure = false
    session_life_time = 86400
  
    [security]
    admin_user = admin
    admin_password = 123456@
    secret_key = fadsgdgfdgfgvr
    disable_gravatar = false
    data_source_proxy_whitelist =
    disable_brute_force_login_protection = false
    cookie_secure = false
    cookie_samesite = lax
    allow_embedding = false
    strict_transport_security = false
    strict_transport_security_max_age_seconds = 86400
    strict_transport_security_preload = false
    strict_transport_security_subdomains = false
    x_content_type_options = false
    x_xss_protection = false

    [auth]
    login_cookie_name = grafana_session_mobin
    login_maximum_inactive_lifetime_days = 7
    login_maximum_lifetime_days = 30
    token_rotation_interval_minutes = 10
    disable_login_form = false
    disable_signout_menu = false
    signout_redirect_url =
    oauth_auto_login = true
    api_key_max_seconds_to_live = -1

    [auth.anonymous]
    enabled = true
    org_role = Admin

