apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nas-plugins-pvc
  namespace: mobin-monitor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: grafana-nas-plugins-pv